# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio_indexer
networks:
  - id: 42161
    start_block: 393625836
    contracts:
      - name: Escrow
        address:
          - 0x886495c7c0502d948ad4cb3764aeae2293664bb8
        handler: src/EventHandlers.ts
        events:
          - event: BuyerIntent(uint256 depositId, address buyer, uint256 amount)
            field_selection:
              transaction_fields:
                - "hash"
          - event: FundsDeposited(uint256 depositId, address seller, string upiId, uint256 remainingFunds, uint256 minimumAmount)
            field_selection:
              transaction_fields:
                - "hash"
          - event: FundsWithdrawn(address seller, uint256 depositId, uint256 amount)
            field_selection:
              transaction_fields:
                - "hash"
          - event: IntentCancelled(address buyer, uint256 depositId)
            field_selection:
              transaction_fields:
                - "hash"
          - event: PaymentClaimed(address buyer, uint256 depositId, uint256 usdcAmount, string upiTransactionId)
            field_selection:
              transaction_fields:
                - "hash"
          - event: ClaimedIntent(address buyer, uint256 depositId, uint256 amount)
            field_selection:
              transaction_fields:
                - "hash"
unordered_multichain_mode: true
preload_handlers: true
