# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio_indexer
networks:
- id: 42161
  start_block: 0
  contracts:
  - name: Escrow
    address:
    - 0x6fF44a88AB945E7742bfE16d54CEDa4061462f48
    handler: src/EventHandlers.ts
    events:
    - event: BuyerIntent(uint256 depositId, address buyer, uint256 amount)
    - event: FundsDeposited(uint256 depositId, address seller, string upiId, uint256 remainingFunds, uint256 minimumAmount)
    - event: FundsWithdrawn(address seller, uint256 depositId, uint256 amount)
    - event: IntentCancelled(address buyer, uint256 depositId)
    - event: PaymentClaimed(address buyer, uint256 usdcAmount, string upiTransactionId)
unordered_multichain_mode: true
preload_handlers: true
